name: stylegan3
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9.20
  - pip=24.2
  - numpy=1.26.4
  - click=8.1.8
  - pillow=8.3.1
  - scipy=1.13.1
  - pytorch=2.5.1
  - tqdm=4.62.2
  - requests=2.26.0
  - pyglfw=2.8.0
  - pyopengl=3.1.5
  - matplotlib=3.4.2
  - imageio=2.9.0
  - imageio-ffmpeg=0.5.1
  - pip:
      - imgui==1.3.0
      - pyspng==0.1.2
